// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import fs from "node:fs";

let dbUrl = process.env.DATABASE_URL || "";

// If DATABASE_URL points to docker service 'postgres:5432' and we are running directly on host (not in container)
if (dbUrl.includes("@postgres:5432") && !fs.existsSync("/.dockerenv")) {
  dbUrl = dbUrl.replace("@postgres:5432", "@localhost:5435");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: dbUrl,
  },
});

