import { Sparkles, RefreshCw, AlertCircle } from 'lucide-react'

/**
 * DashboardInsight — Renders the plain-English LLM process analysis generated by Gemini.
 * Uses OpsCopilot's AI-accent theme tokens (violet glow, borders, and badge styling).
 */
export default function DashboardInsight({ insight, isLoading, isError, onRefresh }) {
  return (
    <div className="rounded-card border border-ai-border bg-ai-bg p-3.5 sm:p-6 shadow-sm relative overflow-hidden transition-all duration-300 animate-fade-in-up">
      {/* Background subtle atmospheric radial glow */}
      <div className="absolute -top-12 -right-12 w-48 h-48 bg-primary/10 rounded-full blur-3xl pointer-events-none" />

      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-3 border-b border-ai-border/40 pb-3">
        <div className="flex items-center gap-2.5">
          <div className="w-8 h-8 rounded-xl bg-primary text-white flex items-center justify-center shadow-[0_0_12px_rgba(109,85,250,0.4)]">
            <Sparkles size={18} className="animate-pulse" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h2 className="font-head text-base font-semibold text-text tracking-tight">
                AI Process Synthesis
              </h2>
              <span className="text-[10px] font-mono px-2 py-0.5 rounded-pill bg-primary text-white font-medium">
                Gemini 2.5
              </span>
            </div>
            <p className="text-xs text-muted">Automated operational bottleneck analysis</p>
          </div>
        </div>

        <button
          onClick={onRefresh}
          disabled={isLoading}
          title="Refresh Insight"
          className="self-start sm:self-auto text-xs font-medium text-muted hover:text-primary flex items-center gap-1.5 px-2.5 py-1 rounded-pill bg-surface/60 border border-border/60 hover:bg-surface transition-all duration-200 cursor-pointer disabled:opacity-50"
        >
          <RefreshCw size={13} className={isLoading ? 'animate-spin text-primary' : ''} />
          <span>{isLoading ? 'Synthesizing...' : 'Refresh AI Take'}</span>
        </button>
      </div>

      {isLoading ? (
        <div className="space-y-2.5 py-2 animate-pulse">
          <div className="h-4 bg-primary/15 rounded-md w-11/12" />
          <div className="h-4 bg-primary/10 rounded-md w-4/5" />
          <div className="h-4 bg-primary/10 rounded-md w-3/4" />
        </div>
      ) : isError ? (
        <div className="flex items-center gap-2 text-xs text-danger py-2">
          <AlertCircle size={15} />
          <span>Could not load AI insight right now. Click refresh to retry.</span>
        </div>
      ) : (
        <div className="text-xs sm:text-sm text-text/90 leading-relaxed font-body">
          {insight?.text || insight || 'No process insights available for this dataset.'}
        </div>
      )}
    </div>
  )
}
